# Generated by Django 5.1.4 on 2025-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shoplist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='participants',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
